name: Sync to Public Blog

on:
  push:
    paths:
      - 'posts/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Management Repo
        uses: actions/checkout@v3

      - name: Pushes to Public Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'posts'
          destination-github-username: 'xkot28'
          destination-repository-name: 'ichikawaTHS_Blog'
          target-directory: 'posts'
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: main
